spring:
  profiles.active: default,extensions,secrets
---
spring:
  profiles: default

  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: 'jdbc:mysql://localhost/CFBroker?autoReconnect=true'
    username: root
    password:

endpoints:
  enabled: false
  info:
    enabled: true
    id: version

info:
  build:
    version: ${version}

server.tomcat.accesslog.enabled: true

com.swisscom.cloud.sb.broker.security.platformUsers:
 - guid: 00000000-0000-0000-0000-000000000000
   users:
   - username: cc_admin
     password: change_me
     role: CF_ADMIN
   - username: cc_ext
     password: change_me
     role: CF_EXT_ADMIN

com.swisscom.cloud.sb.broker.backup:
  retryIntervalInSeconds: 10
  maxRetryDurationInMinutes: 30

com.swisscom.cloud.sb.broker.shield:
  baseUrl: 'https://shield.service.consul:8002'
  apiKey:
  agent: '10.244.2.2:5444'
  jobPrefix: 'SB_CF_'
  targetPrefix: 'SB_CF_'
  storeName: 'local'
  retentionName: 'default'
  scheduleName: 'schedu'

com.swisscom.cloud.sb.broker.service.openwhisk:
  openWhiskProtocol:
  openWhiskHost:
  openWhiskPath:
  openWhiskDbUser:
  openWhiskDbPass:
  openWhiskDbProtocol:
  openWhiskDbPort:
  openWhiskDbHost:
  openWhiskDbLocalUser:
  openWhiskDbHostname:

com.swisscom.cloud.sb.broker.service.mongodbent:
  opsManagerUrl: 'http://opsmanager.service.consul:55000'
  opsManagerUrlForAutomationAgent: '' #This parameter is optional
  opsManagerUser:
  opsManagerApiKey:
  portRange: '27000-40000'
  dbFolder: '/var/vcap/store/mongodb-data'
  libFolder: '/var/vcap/store/mongodb-mms-automation'
  logFolder: '/var/vcap/sys/log/mms-automation-agent'
  authSchemaVersion: 5
  mongoDbVersion: '3.4.3-ent'
  featureCompatibilityVersion: '3.4'
  configureDefaultBackupOptions: true
  snapshotIntervalHours: 6 #Supported values are 6, 8, 12, and 24
  snapshotRetentionDays: 3 # Supported values are 1 - 5
  dailySnapshotRetentionDays: 15 #Supported values are [3, 4, 5, 6, 7, 15, 30, 60, 90, 120, 180, 360]
  weeklySnapshotRetentionWeeks: 6 #Supported values are 1 - 52.
  monthlySnapshotRetentionMonths: 6 # Supported values are 1 - 36
  pointInTimeWindowHours: 24
  retryIntervalInSeconds: 15
  maxRetryDurationInMinutes: 30
  advancedBinding: true
  ipRanges: ['172.16.255.224/27']
  protocols: ['tcp'] # 'tcp,udp,icmp'
  boshDirectorBaseUrl: 'https://localhost:25556'
  boshDirectorUsername:
  boshDirectorPassword:
  openstackkUrl: 'https://localhost:5000/v2.0' #Optional config
  openstackUsername: #Optional config
  openstackPassword: #Optional config
  openstackTenantName: #Optional config
  boshManifestFolder: 'test/resources/bosh'

com.swisscom.cloud.sb.broker.service.kubernetes:
  kubernetesHost: "kubernetes-service-api.service.consul"
  kubernetesPort: "6443"
  kubernetesClientCertificate: |
  kubernetesClientKey: |

com.swisscom.cloud.sb.broker.service.kubernetes.redis.v1:
  kubernetesRedisHost: 'kubernetes-service-node.service.consul'
  retryIntervalInSeconds: 10
  maxRetryDurationInMinutes: 3
  ipRanges: []
  protocols: [] # 'tcp,udp,icmp'
  redisConfigurationDefaults:
    MAX_CONNECTIONS: # Plan
    MAX_DATABASES: # Plan
    QUORUM: # Plan
    REDIS_SERVER_MAX_MEMORY: # Plan
    REDIS_MAX_MEMORY: # Plan
    REDIS_MAX_CPU: # Plan
    SENTINEL_MAX_CPU: # Plan
    SENTINEL_MAX_MEMORY: # Plan
    INFLUXDB_HOST: # Bosh
    INFLUXDB_PORT: 9086 # Bosh
    INFLUXDB_USER: admin # Bosh
    INFLUXDB_PASS: # Bosh
    ENVIRONMENT: # Deployment
    SHIELD_AUTHORIZED_KEYS: # Deployment

com.swisscom.cloud.sb.broker.serviceDefinitions: []

com.swisscom.cloud.sb.broker.serviceTemplates:
  - name: redis
    version: 1.0
    templates:
    - |
      apiVersion: v1
      kind: Namespace
      metadata:
        name:
    - |
      apiVersion: v1
      kind: Deployment
      metadata:
        name: